# Generated by Django 2.0 on 2019-04-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createa_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='메뉴 명')),
                ('description', models.CharField(max_length=50, verbose_name='메뉴 설명')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='가격')),
                ('image', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='메뉴 이미지')),
                ('active', models.BooleanField(verbose_name='활성화 상태')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
