# Generated by Django 2.0 on 2019-04-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
