# Generated by Django 2.0 on 2019-04-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menu_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='count',
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='가격'),
        ),
    ]
