# Generated by Django 2.0 on 2019-04-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_auto_20190425_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d', verbose_name='메뉴 이미지'),
        ),
    ]
