# Generated by Django 2.0 on 2019-04-23 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createa_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(max_length=50, verbose_name='주문 번호')),
                ('shipped_address', models.TextField(verbose_name='배달 주소')),
                ('status', models.CharField(max_length=50, verbose_name='주문 상태')),
                ('total', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='총 금액')),
                ('active', models.BooleanField(verbose_name='활성 상태')),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='구매 고객')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart', verbose_name='장바구니')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
