# Generated by Django 2.0 on 2019-04-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='menus',
            field=models.ManyToManyField(blank=True, to='menus.Menu', verbose_name='메뉴'),
        ),
    ]
