# Generated by Django 2.0 on 2019-04-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_menus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total',
            new_name='total_price',
        ),
    ]
