# Generated by Django 2.0 on 2019-04-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20190425_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(default='1', max_length=100, verbose_name='카트 아이디'),
            preserve_default=False,
        ),
    ]
